M48
; DRILL file {KiCad 7.0.5} date Mon Jul 24 14:20:09 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-24T14:20:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X105.42Y-55.34
T2
X99.42Y-55.34
X105.42Y-55.34
T3
X80.5Y-52.7
X80.5Y-80.85
X122.2Y-52.7
X122.2Y-80.85
T0
M30
